import type { Metadata } from "next";

import Providers from "../components/Providers";

import "./globals.css";
import AppBar from "../components/AppBar";
import { Session } from "next-auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  session,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
  session: Session;
}) {
  return (
    <html lang="en">
      <body>
        <Providers session={session}>
          <AppBar />
          {children}
          {modal}
        </Providers>
      </body>
    </html>
  );
}
