import type { Metadata } from "next";

import Providers from "../components/Providers";

import "./globals.css";
import AppBar from "../components/AppBar";
import { RouteProtector } from "@/components/RouteProtector";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <RouteProtector />
          <AppBar />
          {children}
          {modal}
        </Providers>
      </body>
    </html>
  );
}
